### ISSUE TITLE
Problem scenario ENV

### ISSUE THREAD

**Issue by masbenny** [frankplus/AntonBot#3]
**run test : python3 test.py**
receive env: "‘python’: Permission denied"

**all directory has been changed like this:**
directory file: chmod -R 755 /var/www/html/covidbot/ && chown -R www-data:www-data /var/www/html/covidbot/

**ls -lhd $(which python)**
lrwxrwxrwx 1 www-data www-data 7 May 25 17:13 /var/www/html/covidbot/env/bin/python -> python3

**How to solve this ?**

**Comment by frankplus** [comment]
The problem was that you would need to specify the chess engine path in `config.py`.
Fixed by making the chess engine optional so that it doesn't throw errors. 
Thank you for the issue

**Comment by masbenny** [comment]
**solved!**
